name: publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: fd00/kelger
          path: kelger
      - uses: actions/checkout@v4
        with:
          path: yacp
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - run: bundle install
        working-directory: kelger
      - name: run kelger
        run: |
          mkdir _gh-pages
          kelger/exe/kelger -i yacp -o packages.json
          xz -c -z packages.json > _gh-pages/packages.json.xz
      - uses: actions/upload-pages-artifact@v1
        with:
          path: _gh-pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v2
